<?php declare(strict_types=1);

namespace App\Enums;

use BenSampo\Enum\Enum;

final class Ocorrencias extends Enum
{
    const ABONO = 'ABONO DA CHEFIA POR MOTIVO DE SERVIÇO EXTERNO';
    const AME = 'AFASTAMENTO PARA MANDATO ELETIVO';
    const APG = 'AFASTAMENTO PARA PÓS GRADUAÇÃO STRICTO SENSU';
    const APD = 'AFASTAMENTO PREVENTIVO DISCIPLINAR';
    const AE = 'AFASTAMENTO ELEITORAL';
    const AM = 'ATESTADO MÉDICO – INFERIOR A 05 DIAS';
    const CESSAO = 'CESSÃO';
    const CJT = 'COMPENSAÇÃO DE JORNADA DE TRABALHO';
    const CCI = 'CURSO DE CAPACITAÇÃO INSTITUCIONAL';
    const DS = 'DOAÇÃO DE SANGUE';
    const EV = 'EXAME VESTIBULAR';
    const FH = 'FÉRIAS HOMOLOGADAS';
    const FI = 'FALTA INJUSTIFICADA';
    const GREVE = 'GREVE (MOVIMENTOS PAREDISTAS)';
    const HEL = 'HORÁRIO ESPECIAL PARA LACTANTE';
    const LC = 'LICENÇA CAPACITAÇÃO';
    const LSVAC = 'LICENÇA SEM VENCIMENTOS PARA ACOMPANHAMENTO DE CÔNJUGE';
    const LMDPF = 'LICENÇA POR MOTIVO DE DOENÇA EM PESSOA DA FAMÍLIA';
    const LG = 'LICENÇA GALA';
    const LN = 'LICENÇA NOJO';
    const LP = 'LICENÇA PATERNIDADE';
    const LTIP = 'LICENÇA PARA TRATAR DE INTERESSES PARTICULARES';
    const LTS = 'LICENÇA PARA TRATAMENTO DE SAÚDE';
    const LSM = 'LICENÇA PARA O SERVIÇO MILITAR';
    const LDMC = 'LICENÇA PARA DESEMPENHO DE MANDATO CLASSISTA';
    const LAP = 'LICENÇA PARA ATIVIDADE POLÍTICA';
    const DECL = 'DECLARAÇÃO DE COMPARECIMENTO';
    const TRAB_COVID = 'TRABALHO REMOTO - COVID 19';
    const LIB_AB = 'ABONO DA CHEFIA COM JUSTIFICATIVA';
    const HEE = 'HORÁRIO ESPECIAL PARA ESTUDANTE';
    const ADS_D = 'AÇÃO DE DESENVOLVIMENTO EM SERVIÇO - DIAS';
    const ADS_H = 'AÇÃO DE DESENVOLVIMENTO EM SERVIÇO - HORAS';
    const PEI = 'Pesquisa, Extensão e Inovação';
}
